GET http://localhost:3001/currency/

###

GET http://localhost:3001/currency/:id

###

POST http://localhost:3001/currency/

###

PUT http://localhost:3001/currency/:id

###

DELETE http://localhost:3001/currency/:id

###

GET http://localhost:3001/country/

###

POST http://localhost:3001/country/

###

DELETE http://localhost:3001/country/:id
