GET http://localhost:3001/api/currency/

###

GET http://localhost:3001/api/currency/:id

###

POST http://localhost:3001/api/currency/

###

PUT http://localhost:3001/api/currency/:id/:newRate

###

DELETE http://localhost:3001/api/currency/:id